// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFb1dSxpusWuGdFS37rSYCKMHtTVL4f6M',
    appId: '1:904102701136:web:2d24835defb829b9628955',
    messagingSenderId: '904102701136',
    projectId: 'expense-tracker-2428b',
    authDomain: 'expense-tracker-2428b.firebaseapp.com',
    databaseURL: 'https://expense-tracker-2428b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'expense-tracker-2428b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8dFm0JeWUA4wPahEgnthqSO1TEdyy70o',
    appId: '1:904102701136:android:af3c0623f28414a7628955',
    messagingSenderId: '904102701136',
    projectId: 'expense-tracker-2428b',
    databaseURL: 'https://expense-tracker-2428b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'expense-tracker-2428b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXyEgv1o5nKd9VwiXq0zyM_6pfA6n98-0',
    appId: '1:904102701136:ios:b941f2f60206766f628955',
    messagingSenderId: '904102701136',
    projectId: 'expense-tracker-2428b',
    databaseURL: 'https://expense-tracker-2428b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'expense-tracker-2428b.appspot.com',
    iosBundleId: 'com.example.speseCondivise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXyEgv1o5nKd9VwiXq0zyM_6pfA6n98-0',
    appId: '1:904102701136:ios:66e88a4b59769a08628955',
    messagingSenderId: '904102701136',
    projectId: 'expense-tracker-2428b',
    databaseURL: 'https://expense-tracker-2428b-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'expense-tracker-2428b.appspot.com',
    iosBundleId: 'com.example.speseCondivise.RunnerTests',
  );
}
